@startuml diagrama

class GestorAutobus {
}

class Autobus {
}

class Alquiler {
}

class Cliente {
}

class Matricula {
}

Alquiler -- Autobus
Autobus o-- Matricula
GestorAutobus o-- Autobus
GestorAutobus o-- Cliente 
GestorAutobus o-- Alquiler

@enduml
