@startuml
class Main {
  jda
  moduleManager
  main()
}
class CommandHandler {
  commands
  registerCommands()
  onMessageReceived()
}
CommandHandler --|> ListenerAdapter
class ModuleManager {
  modules
  registerModule()
  enableModule()
  disableModule()
  isModuleEnabled()
}
class ManageCommands {
  onSlashCommandInteraction()
}
ManageCommands --|> ListenerAdapter
class ModCommands {
  onSlashCommandInteraction()
  banUser()
  kickUser()
  muteUser()
}
ModCommands --|> ListenerAdapter
class UserCommands {
  onSlashCommandInteraction()
}
UserCommands --|> ListenerAdapter
class DatabaseManager {
  url
  user
  password
  connection
  connect()
  addPenalty()
  getPenalties()
  close()
}
class EventListener {
  onMessageReceived()
  onMessageReactionAdd()
}
EventListener --|> ListenerAdapter
class GuiManager {
  initializeGui()
  updateGui()
}
class Utils {
  isValidUserId()
  formatPenaltyMessage()
  formatDuration()
}
@enduml
